export const LOGO_CORALY_CREATIVE_CURATION: string;
export const LOGO_CORALY_SPACE_CORAL_ICON: string;
export const BRAND_HERO_HEART_LEAF: string;
export const BRAND_CTA_EXPLORE_CREATE: string;
export const BRAND_VENN_SUSTAINABILITY: string;
export const BRAND_QUOTE_GOOD_DAY: string;
export const MARKETING_SUSTAINABLE_COLLECTION: string;
export const MODEL_LISBON_GREY_BUTTERFLY: string;
export const LIFESTYLE_GUITAR_WALK: string;
export const LIFESTYLE_COFFEE_CHOCOLATE: string;
export const LIFESTYLE_ORCHID_CANDLE: string;
export const BG_WINTER_PINE_SNOW: string;
export const BG_WINTER_NIGHT_STARS: string;
export const BG_WINTER_TYPO_SNOW: string;
export const BG_RAINBOW_SKY: string;
export const BG_AUTUMN_LEAVES_SUN: string;
export const BG_SUNSET_SKY_TREE: string;
export const BG_FOREST_PATH_SUNSET: string;

