'use client';

import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import type { ReactNode } from 'react';

type ThemeName = 'dark' | 'light';
type LanguageCode = 'en' | 'pt' | 'fr' | 'de';

type ExperienceContextValue = {
  theme: ThemeName;
  setTheme: (theme: ThemeName) => void;
  toggleTheme: () => void;
  lang: LanguageCode;
  setLang: (lang: LanguageCode) => void;
  t: (key: string) => string;
};

const LANGUAGES: { code: LanguageCode; label: string; flag: string; name: string }[] = [
  { code: 'en', label: 'EN', flag: 'GB', name: 'English' },
  { code: 'pt', label: 'PT', flag: 'PT', name: 'Portugues' },
  { code: 'fr', label: 'FR', flag: 'FR', name: 'Francais' },
  { code: 'de', label: 'DE', flag: 'DE', name: 'Deutsch' },
];

const TRANSLATIONS: Record<LanguageCode, Record<string, string>> = {
  en: {
    nav_shop: 'Shop',
    nav_learn: 'Learn',
    nav_about: 'About',
    nav_events: 'Events',
    nav_community: 'Community',
    nav_cta: 'Join Waitlist',
    hero_sub: 'Creating a sustainability ecosystem together.',
    hero_cta_primary: 'Explore the Space',
    hero_cta_secondary: 'Join the Waitlist',
    footer_intro: 'Creative community and curation. Building a kinder, more connected world where people and planet thrive together.',
    footer_col_explore: 'Explore',
    footer_col_about: 'About',
    footer_col_connect: 'Connect',
    footer_link_marketplace: 'Marketplace',
    footer_link_coraly_store: 'Coraly Store',
    footer_link_knowledge_hub: 'Knowledge Hub',
    footer_link_events: 'Events',
    footer_link_our_story: 'Our Story',
    footer_link_carolines_mission: "Caroline's Mission",
    footer_link_sustainability: 'Sustainability',
    footer_link_partners: 'Partners',
    footer_link_join_waitlist: 'Join Waitlist',
    'footer_link_@coraly.space': '@coraly.space',
    footer_link_newsletter: 'Newsletter',
    footer_copyright: '© 2025 CORALY SPACE · IP Caroline McGlone · coraly.space · Built by Biz Boosters Ltd',
    footer_legal_privacy: 'Privacy',
    footer_legal_terms: 'Terms',
    footer_legal_gdpr: 'GDPR',
    waitlist_kicker: 'PRE-LAUNCH · JOIN THE MOVEMENT',
    waitlist_title_a: 'Belong. Connect.',
    waitlist_title_b: 'Thrive.',
    waitlist_sub: 'Be among the first to join. Early access, event invites, and community news.',
    waitlist_first_name: 'First name',
    waitlist_email: 'Email address',
    waitlist_role_empty: 'I am a... (choose your role)',
    waitlist_role_creator: 'Creator — artist, designer, innovator',
    waitlist_role_maker: 'Sustainable Maker',
    waitlist_role_consumer: 'Conscious Consumer',
    waitlist_role_educator: 'Educator / University',
    waitlist_role_partner: 'Cultural Partner',
    waitlist_button: 'RESERVE MY SPOT',
    waitlist_success_title: 'You are in.',
    waitlist_success_body: 'Welcome to Coraly Space. We will be in touch before launch.',
  },
  pt: {
    nav_shop: 'Loja',
    nav_learn: 'Conhecimento',
    nav_about: 'Sobre',
    nav_events: 'Eventos',
    nav_community: 'Comunidade',
    nav_cta: 'Lista de Espera',
    hero_sub: 'Criando juntos um ecossistema de sustentabilidade.',
    hero_cta_primary: 'Explorar o Espaco',
    hero_cta_secondary: 'Entrar na Lista',
    footer_intro: 'Comunidade criativa e curadoria. Construindo um mundo mais gentil e conectado onde pessoas e planeta prosperam juntos.',
    footer_col_explore: 'Explorar',
    footer_col_about: 'Sobre',
    footer_col_connect: 'Conectar',
    footer_link_marketplace: 'Mercado',
    footer_link_coraly_store: 'Loja Coraly',
    footer_link_knowledge_hub: 'Centro de Conhecimento',
    footer_link_events: 'Eventos',
    footer_link_our_story: 'Nossa Historia',
    footer_link_carolines_mission: 'Missao da Caroline',
    footer_link_sustainability: 'Sustentabilidade',
    footer_link_partners: 'Parceiros',
    footer_link_join_waitlist: 'Lista de Espera',
    'footer_link_@coraly.space': '@coraly.space',
    footer_link_newsletter: 'Newsletter',
    footer_copyright: '© 2025 CORALY SPACE · IP Caroline McGlone · coraly.space · Criado por Biz Boosters Ltd',
    footer_legal_privacy: 'Privacidade',
    footer_legal_terms: 'Termos',
    footer_legal_gdpr: 'GDPR',
    waitlist_kicker: 'PRE-LANCAMENTO · JUNTE-SE AO MOVIMENTO',
    waitlist_title_a: 'Pertencer. Conectar.',
    waitlist_title_b: 'Prosperar.',
    waitlist_sub: 'Seja uma das primeiras pessoas a entrar. Acesso antecipado, convites para eventos e noticias da comunidade.',
    waitlist_first_name: 'Primeiro nome',
    waitlist_email: 'Email',
    waitlist_role_empty: 'Eu sou... (escolha o seu papel)',
    waitlist_role_creator: 'Criador — artista, designer, inovador',
    waitlist_role_maker: 'Criador sustentavel',
    waitlist_role_consumer: 'Consumidor consciente',
    waitlist_role_educator: 'Educador / Universidade',
    waitlist_role_partner: 'Parceiro cultural',
    waitlist_button: 'RESERVAR O MEU LUGAR',
    waitlist_success_title: 'Voce entrou.',
    waitlist_success_body: 'Bem-vindo ao Coraly Space. Entraremos em contacto antes do lancamento.',
  },
  fr: {
    nav_shop: 'Boutique',
    nav_learn: 'Savoir',
    nav_about: 'A propos',
    nav_events: 'Evenements',
    nav_community: 'Communaute',
    nav_cta: 'Liste Attente',
    hero_sub: 'Creer ensemble un ecosysteme durable.',
    hero_cta_primary: 'Explorer',
    hero_cta_secondary: 'Rejoindre',
    footer_intro: 'Communaute creative et curation. Construire un monde plus doux et connecte ou les personnes et la planete prosperent ensemble.',
    footer_col_explore: 'Explorer',
    footer_col_about: 'A propos',
    footer_col_connect: 'Connecter',
    footer_link_marketplace: 'Marketplace',
    footer_link_coraly_store: 'Boutique Coraly',
    footer_link_knowledge_hub: 'Centre de Savoir',
    footer_link_events: 'Evenements',
    footer_link_our_story: 'Notre histoire',
    footer_link_carolines_mission: 'Mission de Caroline',
    footer_link_sustainability: 'Durabilite',
    footer_link_partners: 'Partenaires',
    footer_link_join_waitlist: 'Liste attente',
    'footer_link_@coraly.space': '@coraly.space',
    footer_link_newsletter: 'Newsletter',
    footer_copyright: '© 2025 CORALY SPACE · IP Caroline McGlone · coraly.space · Cree par Biz Boosters Ltd',
    footer_legal_privacy: 'Confidentialite',
    footer_legal_terms: 'Conditions',
    footer_legal_gdpr: 'GDPR',
    waitlist_kicker: 'PRE-LANCEMENT · REJOINDRE LE MOUVEMENT',
    waitlist_title_a: 'Appartenir. Connecter.',
    waitlist_title_b: 'S epanouir.',
    waitlist_sub: 'Soyez parmi les premiers a rejoindre. Acces anticipe, invitations aux evenements et nouvelles de la communaute.',
    waitlist_first_name: 'Prenom',
    waitlist_email: 'Adresse email',
    waitlist_role_empty: 'Je suis... (choisissez votre role)',
    waitlist_role_creator: 'Createur — artiste, designer, innovateur',
    waitlist_role_maker: 'Createur durable',
    waitlist_role_consumer: 'Consommateur conscient',
    waitlist_role_educator: 'Educateur / Universite',
    waitlist_role_partner: 'Partenaire culturel',
    waitlist_button: 'RESERVER MA PLACE',
    waitlist_success_title: 'Vous etes inscrit.',
    waitlist_success_body: 'Bienvenue chez Coraly Space. Nous vous contacterons avant le lancement.',
  },
  de: {
    nav_shop: 'Shop',
    nav_learn: 'Wissen',
    nav_about: 'Uber uns',
    nav_events: 'Events',
    nav_community: 'Gemeinschaft',
    nav_cta: 'Warteliste',
    hero_sub: 'Gemeinsam ein Nachhaltigkeits-Okosystem aufbauen.',
    hero_cta_primary: 'Entdecken',
    hero_cta_secondary: 'Warteliste',
    footer_intro: 'Kreative Gemeinschaft und Kuration. Wir bauen eine freundlichere, verbundenere Welt, in der Menschen und Planet gemeinsam gedeihen.',
    footer_col_explore: 'Entdecken',
    footer_col_about: 'Uber uns',
    footer_col_connect: 'Verbinden',
    footer_link_marketplace: 'Marktplatz',
    footer_link_coraly_store: 'Coraly Shop',
    footer_link_knowledge_hub: 'Wissenszentrum',
    footer_link_events: 'Events',
    footer_link_our_story: 'Unsere Geschichte',
    footer_link_carolines_mission: 'Carolines Mission',
    footer_link_sustainability: 'Nachhaltigkeit',
    footer_link_partners: 'Partner',
    footer_link_join_waitlist: 'Warteliste',
    'footer_link_@coraly.space': '@coraly.space',
    footer_link_newsletter: 'Newsletter',
    footer_copyright: '© 2025 CORALY SPACE · IP Caroline McGlone · coraly.space · Erstellt von Biz Boosters Ltd',
    footer_legal_privacy: 'Datenschutz',
    footer_legal_terms: 'Bedingungen',
    footer_legal_gdpr: 'GDPR',
    waitlist_kicker: 'VORSTART · WERDE TEIL DER BEWEGUNG',
    waitlist_title_a: 'Dazugehoren. Verbinden.',
    waitlist_title_b: 'Gedeihen.',
    waitlist_sub: 'Sei unter den Ersten. Fruher Zugang, Event-Einladungen und Community-News.',
    waitlist_first_name: 'Vorname',
    waitlist_email: 'E-Mail-Adresse',
    waitlist_role_empty: 'Ich bin... (Rolle auswahlen)',
    waitlist_role_creator: 'Kreative Person — Kunstler, Designer, Innovator',
    waitlist_role_maker: 'Nachhaltiger Maker',
    waitlist_role_consumer: 'Bewusster Konsument',
    waitlist_role_educator: 'Bildung / Universitat',
    waitlist_role_partner: 'Kulturpartner',
    waitlist_button: 'PLATZ RESERVIEREN',
    waitlist_success_title: 'Du bist dabei.',
    waitlist_success_body: 'Willkommen bei Coraly Space. Wir melden uns vor dem Launch.',
  },
};

const PHRASE_TRANSLATIONS: Record<Exclude<LanguageCode, 'en'>, Record<string, string>> = {
  pt: {
    'Shop': 'Loja',
    'Learn': 'Conhecimento',
    'About': 'Sobre',
    'Events': 'Eventos',
    'Community': 'Comunidade',
    'Join Waitlist': 'Lista de Espera',
    'Creating a sustainability ecosystem together.': 'Criando juntos um ecossistema de sustentabilidade.',
    'Explore the Space': 'Explorar o Espaco',
    'Join the Waitlist': 'Entrar na Lista',
    'Five Pillars.': 'Cinco Pilares.',
    'One Ecosystem.': 'Um Ecossistema.',
    'Movement & Activity': 'Movimento e Atividade',
    'Movement': 'Movimento',
    '& Activity': 'e Atividade',
    'Dance, voice, walks, and body-led creative events.': 'Danca, voz, caminhadas e eventos criativos guiados pelo corpo.',
    'Community Marketplace': 'Mercado Comunitario',
    'Coraly Store': 'Loja Coraly',
    'Knowledge Hub': 'Centro de Conhecimento',
    'Social Games': 'Jogos Sociais',
    'You belong here.': 'Voce pertence aqui.',
    'Your information home.': 'A sua casa de informacao.',
    'Free vs Pro': 'Gratis vs Pro',
    'Human Contributors': 'Contribuidores Humanos',
    'Always Free': 'Sempre Gratis',
    'Pro Member': 'Membro Pro',
    'Launching Soon': 'Em Breve',
    'Belong.': 'Pertencer.',
    'Connect.': 'Conectar.',
    'Thrive.': 'Prosperar.',
    'Wear your': 'Vista os seus',
    'values.': 'valores.',
    'Building a kinder,': 'Construindo um mundo mais gentil,',
    'more connected': 'mais conectado',
    'world.': 'mundo.',
    'Learn. Share.': 'Aprenda. Partilhe.',
    'Grow Together.': 'Crescam Juntos.',
    'Move. Create.': 'Mova-se. Crie.',
    'Connect in person.': 'Conecte-se presencialmente.',
    'Book an Event': 'Reservar Evento',
    'Join Online Community': 'Entrar na Comunidade Online',
    'Kids Collection': 'Colecao Infantil',
    'Adult Collection': 'Colecao Adulto',
    'Subscribe': 'Subscrever',
    'Read': 'Ler',
    'Close': 'Fechar',
    "FOUNDER'S STORY": 'HISTORIA DA FUNDADORA',
    'Founder, Coraly Space': 'Fundadora, Coraly Space',
    'Join the Community': 'Entrar na Comunidade',
    'See Our Events': 'Ver Eventos',
    'ABOUT CORALY SPACE': 'SOBRE CORALY SPACE',
    'Story': 'Historia',
    'Mission': 'Missao',
    'Values': 'Valores',
    'Team': 'Equipa',
    'THE FIVE PILLARS': 'OS CINCO PILARES',
    'One ecosystem.': 'Um ecossistema.',
    'Five ways in.': 'Cinco formas de entrar.',
    'TWO SIDES, ONE MISSION': 'DOIS LADOS, UMA MISSAO',
    'The dual': 'A dupla',
    'personality.': 'personalidade.',
    'THE HUMAN BEHIND IT': 'A PESSOA POR TRAS',
    'Come Meet Her': 'Venha Conhece-la',
    'WHAT YOU GET': 'O QUE VOCE RECEBE',
    'Six ways to': 'Seis formas de',
    'explore the space.': 'explorar o espaco.',
    'THE ECOSYSTEM': 'O ECOSSISTEMA',
    'More than a platform.': 'Mais que uma plataforma.',
    'A movement.': 'Um movimento.',
    'Learn Our Mission': 'Conheca a Nossa Missao',
    'OUR PEOPLE': 'AS NOSSAS PESSOAS',
    'Coraly Space is for people who do not fit neatly into one box.': 'Coraly Space e para pessoas que nao cabem facilmente numa unica caixa.',
    'Knowledge, made practical.': 'Conhecimento tornado pratico.',
    'Expert knowledge, community wisdom, and human contributors.': 'Conhecimento especialista, sabedoria comunitaria e contribuidores humanos.',
    'Get started free': 'Comecar gratis',
    'Join Pro waitlist': 'Entrar na lista Pro',
    'CREATIVITY CULTURE & SUSTAINABILITY': 'CRIATIVIDADE CULTURA E SUSTENTABILIDADE',
    'Wear your values.': 'Vista os seus valores.',
    'All Articles': 'Todos os Artigos',
    'ALL ARTICLES': 'TODOS OS ARTIGOS',
    'FEATURED THIS SEASON': 'DESTAQUE DA ESTACAO',
    'SUSTAINABILITY': 'SUSTENTABILIDADE',
    'COMMUNITY': 'COMUNIDADE',
    'CIRCULAR ECONOMY': 'ECONOMIA CIRCULAR',
    'CREATIVE LIVING': 'VIDA CRIATIVA',
    'MENTAL HEALTH': 'SAUDE MENTAL',
    'COMFORT & WELLBEING': 'CONFORTO E BEM-ESTAR',
    'WEEKLY WISDOM': 'SABEDORIA SEMANAL',
    'Get the newsletter.': 'Receba a newsletter.',
    'Stay inspired.': 'Mantenha-se inspirado.',
    'FIND US EVERYWHERE': 'ENCONTRE-NOS EM TODO LADO',
    'PRE-LAUNCH · JOIN THE MOVEMENT': 'PRE-LANCAMENTO · JUNTE-SE AO MOVIMENTO',
    'Belong. Connect.': 'Pertencer. Conectar.',
    'I am a... (choose your role)': 'Eu sou... (escolha o seu papel)',
    'Be among the first to join. Early access, event invites, and community news.': 'Seja uma das primeiras pessoas a entrar. Acesso antecipado, convites para eventos e noticias da comunidade.',
    'RESERVE MY SPOT': 'RESERVAR O MEU LUGAR',
    'First name': 'Primeiro nome',
    'Email address': 'Email',
    'Organic cotton. On-demand. Zero waste. Every piece made by Teemill — so nothing is made until you order it.': 'Algodao organico. Sob demanda. Zero desperdicio. Cada peca e feita pela Teemill, por isso nada e produzido antes do seu pedido.',
    'Full Collection': 'Colecao Completa',
    'ADD TO BAG +': 'ADICIONAR AO SACO +',
    'ADD +': 'ADICIONAR +',
    'AS WORN': 'COMO USADO',
    'ICON': 'ICONE',
    'LOVED': 'ADORADO',
    'WHITE · WOMEN\'S': 'BRANCO · FEMININO',
    'WHITE · UNISEX': 'BRANCO · UNISSEX',
    'BLACK · STATEMENT': 'PRETO · DECLARACAO',
    'GREY · HOODIE': 'CINZA · HOODIE',
    'Weekly community digest': 'Resumo semanal da comunidade',
    'Public forums and discussions': 'Foruns publicos e discussoes',
    'Basic articles and guides': 'Artigos e guias basicos',
    'Monthly virtual events': 'Eventos virtuais mensais',
    'Coraly newsletter': 'Newsletter Coraly',
    'Free sustainability challenges': 'Desafios gratuitos de sustentabilidade',
    'Courses and masterclasses': 'Cursos e masterclasses',
    'Expert-led workshops': 'Workshops liderados por especialistas',
    'Peer mentoring circles': 'Circulos de mentoria entre pares',
    'Business tools for makers': 'Ferramentas de negocio para criadores',
    'Burnout recovery programmes': 'Programas de recuperacao de burnout',
    'Contributor-only content': 'Conteudo exclusivo para contribuidores',
    '/month': '/mes',
    'Dancers & Movers': 'Dancarinos e Pessoas em Movimento',
    'Active People & Explorers': 'Pessoas Ativas e Exploradores',
    'Solopreneurs & Small Businesses': 'Solopreneurs e Pequenas Empresas',
    'Neurodivergent Folks': 'Pessoas Neurodivergentes',
    'Parents & Carers': 'Pais e Cuidadores',
    'Caring Professions': 'Profissoes de Cuidado',
    'Community Leaders': 'Lideres Comunitarios',
    'Virtuoso Creatives': 'Criativos Virtuosos',
    'LGBTQIA+ Community': 'Comunidade LGBTQIA+',
    'Cultural Leaders & Diaspora': 'Lideres Culturais e Diaspora',
    'Sustainable Makers': 'Criadores Sustentaveis',
    'Universities & Educators': 'Universidades e Educadores',
    'Active explorers who connect through movement and embodied creativity.': 'Exploradores ativos que se conectam atraves do movimento e da criatividade corporal.',
    'Walkers, adventurers, nature-lovers, and people who need connection in motion.': 'Caminhantes, aventureiros, amantes da natureza e pessoas que precisam de conexao em movimento.',
    'Independent founders building meaningful work on their own terms.': 'Fundadores independentes criando trabalho com significado nos seus proprios termos.',
    'Different ways of thinking, creating, processing, and connecting.': 'Diferentes formas de pensar, criar, processar e conectar.',
    'People holding families, communities, and care responsibilities who need support too.': 'Pessoas que sustentam familias, comunidades e responsabilidades de cuidado, e que tambem precisam de apoio.',
    'Teachers, nurses, counsellors, and helpers carrying burnout and giving so much.': 'Professores, enfermeiros, terapeutas e cuidadores que carregam burnout e dao tanto.',
    'Bridge-builders and space-holders finding support for themselves too.': 'Construtores de pontes e guardioes de espacos que tambem encontram apoio para si.',
    'High-performing creatives looking for peers who understand the pressure.': 'Criativos de alto desempenho procurando pares que entendem a pressao.',
    'A visible, celebratory space for safety and authentic belonging.': 'Um espaco visivel e celebratorio para seguranca e pertencimento autentico.',
    'Heritage keepers and cultural connectors enriching every room they enter.': 'Guardioes de heranca e conectores culturais que enriquecem todos os espacos.',
    'Artists, makers, upcyclers, and creators building with the planet in mind.': 'Artistas, makers, upcyclers e criadores construindo com o planeta em mente.',
    'Learning communities, students, and educators building practical futures.': 'Comunidades de aprendizagem, estudantes e educadores criando futuros praticos.',
    'Movement & Dance': 'Movimento e Danca',
    'Sustainability Makers': 'Criadores de Sustentabilidade',
    'Neurodivergent Coaches': 'Coaches Neurodivergentes',
    'Solopreneur Mentors': 'Mentores de Solopreneurs',
    'Somatic practice, creative movement, and active wellbeing.': 'Pratica somatica, movimento criativo e bem-estar ativo.',
    'Circular economy, sourcing, and low-waste living guides.': 'Guias de economia circular, sourcing e vida com pouco desperdicio.',
    'Friendly systems, executive function tools, and inclusive support.': 'Sistemas amigaveis, ferramentas de funcao executiva e apoio inclusivo.',
    'Business confidence, client attraction, and burnout prevention.': 'Confianca nos negocios, atracao de clientes e prevencao de burnout.',
  },
  fr: {
    'Shop': 'Boutique',
    'Learn': 'Savoir',
    'About': 'A propos',
    'Events': 'Evenements',
    'Community': 'Communaute',
    'Join Waitlist': 'Liste Attente',
    'Creating a sustainability ecosystem together.': 'Creer ensemble un ecosysteme durable.',
    'Explore the Space': 'Explorer',
    'Join the Waitlist': 'Rejoindre',
    'Five Pillars.': 'Cinq Piliers.',
    'One Ecosystem.': 'Un Ecosysteme.',
    'Movement & Activity': 'Mouvement et Activite',
    'Movement': 'Mouvement',
    '& Activity': 'et Activite',
    'Dance, voice, walks, and body-led creative events.': 'Danse, voix, promenades et evenements creatifs corporels.',
    'Community Marketplace': 'Marketplace Communautaire',
    'Coraly Store': 'Boutique Coraly',
    'Knowledge Hub': 'Centre de Savoir',
    'Social Games': 'Jeux Sociaux',
    'You belong here.': 'Vous avez votre place ici.',
    'Your information home.': 'Votre maison d information.',
    'Free vs Pro': 'Gratuit vs Pro',
    'Human Contributors': 'Contributeurs Humains',
    'Always Free': 'Toujours Gratuit',
    'Pro Member': 'Membre Pro',
    'Launching Soon': 'Bientot',
    'Belong.': 'Appartenir.',
    'Connect.': 'Connecter.',
    'Thrive.': 'S epanouir.',
    'Wear your': 'Portez vos',
    'values.': 'valeurs.',
    'Building a kinder,': 'Construire un monde plus doux,',
    'more connected': 'plus connecte',
    'world.': 'monde.',
    'Learn. Share.': 'Apprendre. Partager.',
    'Grow Together.': 'Grandir Ensemble.',
    'Move. Create.': 'Bouger. Creer.',
    'Connect in person.': 'Se connecter en personne.',
    'Book an Event': 'Reserver un evenement',
    'Join Online Community': 'Rejoindre la communaute',
    'Kids Collection': 'Collection Enfants',
    'Adult Collection': 'Collection Adultes',
    'Subscribe': 'S abonner',
    'Read': 'Lire',
    'Close': 'Fermer',
    "FOUNDER'S STORY": 'HISTOIRE DE LA FONDATRICE',
    'Founder, Coraly Space': 'Fondatrice, Coraly Space',
    'Join the Community': 'Rejoindre la communaute',
    'See Our Events': 'Voir nos evenements',
    'ABOUT CORALY SPACE': 'A PROPOS DE CORALY SPACE',
    'Story': 'Histoire',
    'Mission': 'Mission',
    'Values': 'Valeurs',
    'Team': 'Equipe',
    'THE FIVE PILLARS': 'LES CINQ PILIERS',
    'One ecosystem.': 'Un ecosysteme.',
    'Five ways in.': 'Cinq manieres d entrer.',
    'TWO SIDES, ONE MISSION': 'DEUX COTES, UNE MISSION',
    'The dual': 'La double',
    'personality.': 'personnalite.',
    'THE HUMAN BEHIND IT': 'LA PERSONNE DERRIERE',
    'Come Meet Her': 'Venez la rencontrer',
    'WHAT YOU GET': 'CE QUE VOUS RECEVEZ',
    'Six ways to': 'Six facons d',
    'explore the space.': 'explorer l espace.',
    'THE ECOSYSTEM': 'L ECOSYSTEME',
    'More than a platform.': 'Plus qu une plateforme.',
    'A movement.': 'Un mouvement.',
    'Learn Our Mission': 'Decouvrir notre mission',
    'OUR PEOPLE': 'NOS PERSONNES',
    'Coraly Space is for people who do not fit neatly into one box.': 'Coraly Space est pour les personnes qui ne rentrent pas dans une seule case.',
    'Knowledge, made practical.': 'Le savoir, rendu pratique.',
    'Expert knowledge, community wisdom, and human contributors.': 'Savoir expert, sagesse communautaire et contributeurs humains.',
    'Get started free': 'Commencer gratuitement',
    'Join Pro waitlist': 'Rejoindre la liste Pro',
    'CREATIVITY CULTURE & SUSTAINABILITY': 'CREATIVITE CULTURE ET DURABILITE',
    'Wear your values.': 'Portez vos valeurs.',
    'All Articles': 'Tous les articles',
    'ALL ARTICLES': 'TOUS LES ARTICLES',
    'FEATURED THIS SEASON': 'A LA UNE CETTE SAISON',
    'SUSTAINABILITY': 'DURABILITE',
    'COMMUNITY': 'COMMUNAUTE',
    'CIRCULAR ECONOMY': 'ECONOMIE CIRCULAIRE',
    'CREATIVE LIVING': 'VIE CREATIVE',
    'MENTAL HEALTH': 'SANTE MENTALE',
    'COMFORT & WELLBEING': 'CONFORT ET BIEN-ETRE',
    'WEEKLY WISDOM': 'SAGESSE HEBDOMADAIRE',
    'Get the newsletter.': 'Recevez la newsletter.',
    'Stay inspired.': 'Restez inspire.',
    'FIND US EVERYWHERE': 'RETROUVEZ-NOUS PARTOUT',
    'PRE-LAUNCH · JOIN THE MOVEMENT': 'PRE-LANCEMENT · REJOINDRE LE MOUVEMENT',
    'Belong. Connect.': 'Appartenir. Connecter.',
    'I am a... (choose your role)': 'Je suis... (choisissez votre role)',
    'Be among the first to join. Early access, event invites, and community news.': 'Soyez parmi les premiers a rejoindre. Acces anticipe, invitations aux evenements et nouvelles de la communaute.',
    'RESERVE MY SPOT': 'RESERVER MA PLACE',
    'First name': 'Prenom',
    'Email address': 'Adresse email',
    'Organic cotton. On-demand. Zero waste. Every piece made by Teemill — so nothing is made until you order it.': 'Coton biologique. A la demande. Zero gaspillage. Chaque piece est fabriquee par Teemill, donc rien n est produit avant votre commande.',
    'Full Collection': 'Collection complete',
    'ADD TO BAG +': 'AJOUTER AU PANIER +',
    'ADD +': 'AJOUTER +',
    'AS WORN': 'PORTE',
    'ICON': 'ICONE',
    'LOVED': 'AIME',
    'WHITE · WOMEN\'S': 'BLANC · FEMME',
    'WHITE · UNISEX': 'BLANC · UNISEXE',
    'BLACK · STATEMENT': 'NOIR · STATEMENT',
    'GREY · HOODIE': 'GRIS · HOODIE',
    'Weekly community digest': 'Resume hebdomadaire de la communaute',
    'Public forums and discussions': 'Forums publics et discussions',
    'Basic articles and guides': 'Articles et guides de base',
    'Monthly virtual events': 'Evenements virtuels mensuels',
    'Coraly newsletter': 'Newsletter Coraly',
    'Free sustainability challenges': 'Defis gratuits de durabilite',
    'Courses and masterclasses': 'Cours et masterclasses',
    'Expert-led workshops': 'Ateliers animes par des experts',
    'Peer mentoring circles': 'Cercles de mentorat entre pairs',
    'Business tools for makers': 'Outils business pour createurs',
    'Burnout recovery programmes': 'Programmes de recuperation du burnout',
    'Contributor-only content': 'Contenu reserve aux contributeurs',
    '/month': '/mois',
    'Dancers & Movers': 'Danseurs et personnes en mouvement',
    'Active People & Explorers': 'Personnes actives et explorateurs',
    'Solopreneurs & Small Businesses': 'Solopreneurs et petites entreprises',
    'Neurodivergent Folks': 'Personnes neurodivergentes',
    'Parents & Carers': 'Parents et aidants',
    'Caring Professions': 'Professions du soin',
    'Community Leaders': 'Leaders communautaires',
    'Virtuoso Creatives': 'Creatifs virtuoses',
    'LGBTQIA+ Community': 'Communaute LGBTQIA+',
    'Cultural Leaders & Diaspora': 'Leaders culturels et diaspora',
    'Sustainable Makers': 'Createurs durables',
    'Universities & Educators': 'Universites et educateurs',
    'Active explorers who connect through movement and embodied creativity.': 'Explorateurs actifs qui se connectent par le mouvement et la creativite corporelle.',
    'Walkers, adventurers, nature-lovers, and people who need connection in motion.': 'Marcheurs, aventuriers, amoureux de la nature et personnes qui ont besoin de connexion en mouvement.',
    'Independent founders building meaningful work on their own terms.': 'Fondateurs independants qui construisent un travail porteur de sens selon leurs propres termes.',
    'Different ways of thinking, creating, processing, and connecting.': 'Differentes facons de penser, creer, traiter et se connecter.',
    'People holding families, communities, and care responsibilities who need support too.': 'Personnes qui portent familles, communautes et responsabilites de soin, et qui ont aussi besoin de soutien.',
    'Teachers, nurses, counsellors, and helpers carrying burnout and giving so much.': 'Enseignants, infirmiers, conseillers et aidants qui portent le burnout tout en donnant beaucoup.',
    'Bridge-builders and space-holders finding support for themselves too.': 'Createurs de liens et gardiens d espaces qui trouvent aussi du soutien pour eux-memes.',
    'High-performing creatives looking for peers who understand the pressure.': 'Creatifs performants qui cherchent des pairs comprenant la pression.',
    'A visible, celebratory space for safety and authentic belonging.': 'Un espace visible et celebratoire pour la securite et l appartenance authentique.',
    'Heritage keepers and cultural connectors enriching every room they enter.': 'Gardiens d heritage et connecteurs culturels qui enrichissent chaque espace.',
    'Artists, makers, upcyclers, and creators building with the planet in mind.': 'Artistes, makers, upcycleurs et createurs qui construisent avec la planete en tete.',
    'Learning communities, students, and educators building practical futures.': 'Communautes d apprentissage, etudiants et educateurs qui construisent des futurs pratiques.',
    'Movement & Dance': 'Mouvement et danse',
    'Sustainability Makers': 'Createurs de durabilite',
    'Neurodivergent Coaches': 'Coachs neurodivergents',
    'Solopreneur Mentors': 'Mentors solopreneurs',
    'Somatic practice, creative movement, and active wellbeing.': 'Pratique somatique, mouvement creatif et bien-etre actif.',
    'Circular economy, sourcing, and low-waste living guides.': 'Guides d economie circulaire, sourcing et vie a faible dechet.',
    'Friendly systems, executive function tools, and inclusive support.': 'Systemes accessibles, outils de fonction executive et soutien inclusif.',
    'Business confidence, client attraction, and burnout prevention.': 'Confiance business, attraction de clients et prevention du burnout.',
  },
  de: {
    'Shop': 'Shop',
    'Learn': 'Wissen',
    'About': 'Uber uns',
    'Events': 'Events',
    'Community': 'Gemeinschaft',
    'Join Waitlist': 'Warteliste',
    'Creating a sustainability ecosystem together.': 'Gemeinsam ein Nachhaltigkeits-Okosystem aufbauen.',
    'Explore the Space': 'Entdecken',
    'Join the Waitlist': 'Warteliste',
    'Five Pillars.': 'Funf Saulen.',
    'One Ecosystem.': 'Ein Okosystem.',
    'Movement & Activity': 'Bewegung und Aktivitat',
    'Movement': 'Bewegung',
    '& Activity': 'und Aktivitat',
    'Dance, voice, walks, and body-led creative events.': 'Tanz, Stimme, Spaziergange und korperbasierte kreative Events.',
    'Community Marketplace': 'Community-Marktplatz',
    'Coraly Store': 'Coraly Shop',
    'Knowledge Hub': 'Wissenszentrum',
    'Social Games': 'Soziale Spiele',
    'You belong here.': 'Du gehorst hierher.',
    'Your information home.': 'Dein Informations-Zuhause.',
    'Free vs Pro': 'Kostenlos vs Pro',
    'Human Contributors': 'Menschliche Beitrage',
    'Always Free': 'Immer Kostenlos',
    'Pro Member': 'Pro Mitglied',
    'Launching Soon': 'Bald Verfugbar',
    'Belong.': 'Dazugehoren.',
    'Connect.': 'Verbinden.',
    'Thrive.': 'Gedeihen.',
    'Wear your': 'Trage deine',
    'values.': 'Werte.',
    'Building a kinder,': 'Eine freundlichere,',
    'more connected': 'verbundenere',
    'world.': 'Welt bauen.',
    'Learn. Share.': 'Lernen. Teilen.',
    'Grow Together.': 'Gemeinsam Wachsen.',
    'Move. Create.': 'Bewegen. Erschaffen.',
    'Connect in person.': 'Personlich verbinden.',
    'Book an Event': 'Event buchen',
    'Join Online Community': 'Online-Community beitreten',
    'Kids Collection': 'Kinderkollektion',
    'Adult Collection': 'Erwachsenenkollektion',
    'Subscribe': 'Abonnieren',
    'Read': 'Lesen',
    'Close': 'Schliessen',
    "FOUNDER'S STORY": 'GESCHICHTE DER GRUENDERIN',
    'Founder, Coraly Space': 'Gruenderin, Coraly Space',
    'Join the Community': 'Community beitreten',
    'See Our Events': 'Events ansehen',
    'ABOUT CORALY SPACE': 'UEBER CORALY SPACE',
    'Story': 'Geschichte',
    'Mission': 'Mission',
    'Values': 'Werte',
    'Team': 'Team',
    'THE FIVE PILLARS': 'DIE FUENF SAEULEN',
    'One ecosystem.': 'Ein Okosystem.',
    'Five ways in.': 'Fuenf Wege hinein.',
    'TWO SIDES, ONE MISSION': 'ZWEI SEITEN, EINE MISSION',
    'The dual': 'Die doppelte',
    'personality.': 'Persoenlichkeit.',
    'THE HUMAN BEHIND IT': 'DER MENSCH DAHINTER',
    'Come Meet Her': 'Lerne sie kennen',
    'WHAT YOU GET': 'WAS DU BEKOMMST',
    'Six ways to': 'Sechs Wege,',
    'explore the space.': 'den Raum zu erkunden.',
    'THE ECOSYSTEM': 'DAS OKOSYSTEM',
    'More than a platform.': 'Mehr als eine Plattform.',
    'A movement.': 'Eine Bewegung.',
    'Learn Our Mission': 'Unsere Mission kennenlernen',
    'OUR PEOPLE': 'UNSERE MENSCHEN',
    'Coraly Space is for people who do not fit neatly into one box.': 'Coraly Space ist fuer Menschen, die nicht einfach in eine Schublade passen.',
    'Knowledge, made practical.': 'Wissen, praktisch gemacht.',
    'Expert knowledge, community wisdom, and human contributors.': 'Expertenwissen, Community-Weisheit und menschliche Beitrage.',
    'Get started free': 'Kostenlos starten',
    'Join Pro waitlist': 'Pro-Warteliste beitreten',
    'CREATIVITY CULTURE & SUSTAINABILITY': 'KREATIVITAET KULTUR UND NACHHALTIGKEIT',
    'Wear your values.': 'Trage deine Werte.',
    'All Articles': 'Alle Artikel',
    'ALL ARTICLES': 'ALLE ARTIKEL',
    'FEATURED THIS SEASON': 'DIESE SAISON IM FOKUS',
    'SUSTAINABILITY': 'NACHHALTIGKEIT',
    'COMMUNITY': 'GEMEINSCHAFT',
    'CIRCULAR ECONOMY': 'KREISLAUFWIRTSCHAFT',
    'CREATIVE LIVING': 'KREATIVES LEBEN',
    'MENTAL HEALTH': 'MENTALE GESUNDHEIT',
    'COMFORT & WELLBEING': 'KOMFORT UND WOHLBEFINDEN',
    'WEEKLY WISDOM': 'WOECHENTLICHE WEISHEIT',
    'Get the newsletter.': 'Newsletter erhalten.',
    'Stay inspired.': 'Inspiriert bleiben.',
    'FIND US EVERYWHERE': 'FINDE UNS UEBERALL',
    'PRE-LAUNCH · JOIN THE MOVEMENT': 'VORSTART · WERDE TEIL DER BEWEGUNG',
    'Belong. Connect.': 'Dazugehoeren. Verbinden.',
    'I am a... (choose your role)': 'Ich bin... (Rolle auswaehlen)',
    'Be among the first to join. Early access, event invites, and community news.': 'Sei unter den Ersten. Frueher Zugang, Event-Einladungen und Community-News.',
    'RESERVE MY SPOT': 'PLATZ RESERVIEREN',
    'First name': 'Vorname',
    'Email address': 'E-Mail-Adresse',
    'Organic cotton. On-demand. Zero waste. Every piece made by Teemill — so nothing is made until you order it.': 'Bio-Baumwolle. Auf Abruf. Kein Abfall. Jedes Stueck wird von Teemill gefertigt, also erst produziert, wenn du bestellst.',
    'Full Collection': 'Ganze Kollektion',
    'ADD TO BAG +': 'IN DEN WARENKORB +',
    'ADD +': 'HINZUFUEGEN +',
    'AS WORN': 'GETRAGEN',
    'ICON': 'IKONE',
    'LOVED': 'BELIEBT',
    'WHITE · WOMEN\'S': 'WEISS · DAMEN',
    'WHITE · UNISEX': 'WEISS · UNISEX',
    'BLACK · STATEMENT': 'SCHWARZ · STATEMENT',
    'GREY · HOODIE': 'GRAU · HOODIE',
    'Weekly community digest': 'Woechentlicher Community-Ueberblick',
    'Public forums and discussions': 'Oeffentliche Foren und Diskussionen',
    'Basic articles and guides': 'Basisartikel und Leitfaeden',
    'Monthly virtual events': 'Monatliche virtuelle Events',
    'Coraly newsletter': 'Coraly Newsletter',
    'Free sustainability challenges': 'Kostenlose Nachhaltigkeits-Challenges',
    'Courses and masterclasses': 'Kurse und Masterclasses',
    'Expert-led workshops': 'Von Experten geleitete Workshops',
    'Peer mentoring circles': 'Peer-Mentoring-Kreise',
    'Business tools for makers': 'Business-Tools fuer Maker',
    'Burnout recovery programmes': 'Burnout-Erholungsprogramme',
    'Contributor-only content': 'Nur fuer Beitragende',
    '/month': '/Monat',
    'Dancers & Movers': 'Taenzer und Bewegungsmenschen',
    'Active People & Explorers': 'Aktive Menschen und Entdecker',
    'Solopreneurs & Small Businesses': 'Solopreneure und kleine Unternehmen',
    'Neurodivergent Folks': 'Neurodivergente Menschen',
    'Parents & Carers': 'Eltern und Pflegende',
    'Caring Professions': 'Pflege- und Care-Berufe',
    'Community Leaders': 'Community-Leader',
    'Virtuoso Creatives': 'Virtuose Kreative',
    'LGBTQIA+ Community': 'LGBTQIA+ Community',
    'Cultural Leaders & Diaspora': 'Kulturleader und Diaspora',
    'Sustainable Makers': 'Nachhaltige Maker',
    'Universities & Educators': 'Universitaeten und Lehrende',
    'Active explorers who connect through movement and embodied creativity.': 'Aktive Entdecker, die sich durch Bewegung und verkörperte Kreativitaet verbinden.',
    'Walkers, adventurers, nature-lovers, and people who need connection in motion.': 'Spaziergaenger, Abenteurer, Naturliebhaber und Menschen, die Verbindung in Bewegung brauchen.',
    'Independent founders building meaningful work on their own terms.': 'Unabhaengige Gruender, die sinnvolle Arbeit nach eigenen Bedingungen aufbauen.',
    'Different ways of thinking, creating, processing, and connecting.': 'Andere Arten zu denken, zu erschaffen, zu verarbeiten und sich zu verbinden.',
    'People holding families, communities, and care responsibilities who need support too.': 'Menschen, die Familien, Gemeinschaften und Care-Verantwortung tragen und selbst Unterstuetzung brauchen.',
    'Teachers, nurses, counsellors, and helpers carrying burnout and giving so much.': 'Lehrkraefte, Pflegekraefte, Berater und Helfende, die Burnout tragen und so viel geben.',
    'Bridge-builders and space-holders finding support for themselves too.': 'Brueckenbauer und Raumhalter, die auch fuer sich selbst Unterstuetzung finden.',
    'High-performing creatives looking for peers who understand the pressure.': 'Leistungsstarke Kreative, die Gleichgesinnte suchen, die den Druck verstehen.',
    'A visible, celebratory space for safety and authentic belonging.': 'Ein sichtbarer, feiernder Raum fuer Sicherheit und echtes Zugehoeren.',
    'Heritage keepers and cultural connectors enriching every room they enter.': 'Hueter von Herkunft und kulturelle Verbinder, die jeden Raum bereichern.',
    'Artists, makers, upcyclers, and creators building with the planet in mind.': 'Kuenstler, Maker, Upcycler und Kreative, die mit Blick auf den Planeten bauen.',
    'Learning communities, students, and educators building practical futures.': 'Lerngemeinschaften, Studierende und Lehrende, die praktische Zukuenfte gestalten.',
    'Movement & Dance': 'Bewegung und Tanz',
    'Sustainability Makers': 'Nachhaltigkeits-Maker',
    'Neurodivergent Coaches': 'Neurodivergente Coaches',
    'Solopreneur Mentors': 'Solopreneur-Mentoren',
    'Somatic practice, creative movement, and active wellbeing.': 'Somatische Praxis, kreative Bewegung und aktives Wohlbefinden.',
    'Circular economy, sourcing, and low-waste living guides.': 'Leitfaeden fuer Kreislaufwirtschaft, Sourcing und abfallarmes Leben.',
    'Friendly systems, executive function tools, and inclusive support.': 'Freundliche Systeme, Tools fuer exekutive Funktionen und inklusive Unterstuetzung.',
    'Business confidence, client attraction, and burnout prevention.': 'Business-Sicherheit, Kundengewinnung und Burnout-Praevention.',
  },
};

const EXTRA_PHRASE_TRANSLATIONS: Record<Exclude<LanguageCode, 'en'>, Record<string, string>> = {
  pt: {
    'SUSTAINABILITY ECOSYSTEM': 'ECOSSISTEMA DE SUSTENTABILIDADE',
    'Creative': 'Criatividade',
    'Curation.': 'Curadoria.',
    'BELONG · CONNECT · THRIVE': 'PERTENCER · CONECTAR · PROSPERAR',
    'COMMUNITY IN MOTION': 'COMUNIDADE EM MOVIMENTO',
    'Explorers.': 'Exploradores.',
    'Every one of them.': 'Cada um deles.',
    'View All Community': 'Ver Toda a Comunidade',
    'Meet Caroline': 'Conhecer Caroline',
    'Our Events': 'Nossos Eventos',
    'ONE CORALY · TWO EXPRESSIONS': 'UMA CORALY · DUAS EXPRESSOES',
    'The digital space': 'O espaco digital',
    'and the human touch.': 'e o toque humano.',
    'Coraly Space holds the tech-enabled community ecosystem, while Coraly UK brings the softer world of movement, care, culture, and sustainable living. Together they make the brand feel complete.': 'Coraly Space sustenta o ecossistema comunitario com tecnologia, enquanto Coraly UK traz o mundo mais suave do movimento, cuidado, cultura e vida sustentavel. Juntas, tornam a marca completa.',
    'Marketplace, knowledge, social play, and community belonging.': 'Mercado, conhecimento, jogo social e pertencimento comunitario.',
    'Movement, care, culture, and sustainable everyday living.': 'Movimento, cuidado, cultura e vida diaria sustentavel.',
    'Dance, Create, Sing, Move. @coraly.space': 'Dance, Crie, Cante, Mova-se. @coraly.space',
    'Care & Recovery': 'Cuidado e Recuperacao',
    'Creative Culture': 'Cultura Criativa',
    'Sustainable Living': 'Vida Sustentavel',
    'Gentle rituals for carers, teachers, nurses, and burnt-out leaders.': 'Rituais suaves para cuidadores, professores, enfermeiros e lideres esgotados.',
    'Workshops, stories, and collaborations for makers with depth.': 'Workshops, historias e colaboracoes para criadores com profundidade.',
    'Low-waste style, nature-led habits, and beautiful everyday choices.': 'Estilo com pouco desperdicio, habitos guiados pela natureza e belas escolhas diarias.',
    'Learn. Share. Grow Together.': 'Aprenda. Partilhe. Crescam Juntos.',
    'Every season brings a new chapter. Winter is not an absence — it\'s a transformation.': 'Cada estacao traz um novo capitulo. O inverno nao e ausencia — e transformacao.',
    'Winter Wonderlands': 'Maravilhas de Inverno',
    'Quality Over Quantity': 'Qualidade Acima de Quantidade',
    'Busy Lives, Creativity & Comfort': 'Vidas Ocupadas, Criatividade e Conforto',
    'Read': 'Ler',
    'read': 'leitura',
    'Full Collection': 'Colecao Completa',
    'Butterfly & Moon Tee': 'T-shirt Borboleta e Lua',
    'Moon Phase Tee': 'T-shirt Fases da Lua',
    'REWILD Tee': 'T-shirt REWILD',
    'Coral Rose Hoodie': 'Hoodie Rosa Coral',
    'THE FULL RANGE': 'A GAMA COMPLETA',
    'Little explorers,': 'Pequenos exploradores,',
    'big hearts.': 'grandes coracoes.',
    'Wear it.': 'Use.',
    'Mean it.': 'Com significado.',
    'Every piece.': 'Cada peca.',
    'A statement.': 'Uma declaracao.',
    'Join to Shop Early': 'Entrar para Comprar Primeiro',
    'Visit Teemill Store': 'Visitar Loja Teemill',
    'ICON PIECE': 'PECA ICONE',
    'STATEMENT PIECE': 'PECA DECLARACAO',
    'BLACK · STATEMENT · ORGANIC COTTON': 'PRETO · DECLARACAO · ALGODAO ORGANICO',
    'Add to Bag': 'Adicionar ao Saco',
    'LIVE EVENTS & GATHERINGS': 'EVENTOS AO VIVO E ENCONTROS',
    'SIGNATURE EVENT': 'EVENTO ASSINATURA',
    'RECURRING · IN PERSON': 'RECORRENTE · PRESENCIAL',
    'Dance & Voice': 'Danca e Voz',
    'Workshop.': 'Workshop.',
    'Book Now': 'Reservar Agora',
    'Ask a Question': 'Fazer uma Pergunta',
    'WANT TO COLLABORATE?': 'QUER COLABORAR?',
    'Host with': 'Organize com',
    'Get in Touch': 'Entrar em Contacto',
    'Learn About Us': 'Conheca-nos',
    'Join the Conversation': 'Entrar na Conversa',
    'People. Planet.': 'Pessoas. Planeta.',
    'Profit.': 'Lucro.',
    'NO ARTICLES IN THIS CATEGORY YET — CHECK BACK SOON': 'AINDA NAO HA ARTIGOS NESTA CATEGORIA — VOLTE EM BREVE',
    'your@email.com': 'seu@email.com',
    'Marketplace': 'Mercado',
    'Live Events': 'Eventos Ao Vivo',
    'Community Space': 'Espaco Comunitario',
    'Impact Tracking': 'Acompanhamento de Impacto',
    'Adults are lonely': 'Adultos sentem solidao',
    'Communities': 'Comunidades',
    'Creativity': 'Criatividade',
    'Instagram': 'Instagram',
    'Web': 'Web',
    'Email': 'Email',
    'Platform': 'Plataforma',
    'Join the Space': 'Entrar no Espaco',
    "See What's On": 'Ver Programacao',
    'EVERY EXPLORER IS WELCOME': 'TODO EXPLORADOR E BEM-VINDO',
    'Hybrid Events': 'Eventos Hibridos',
    'Online Community': 'Comunidade Online',
    'Curated Retail': 'Retalho Curado',
    'Yes, that\'s a community member': 'Sim, e um membro da comunidade',
    'with the Gruffalo.': 'com o Gruffalo.',
    'Dark. Techy. Community platform. Where explorers gather, trade, learn, and play.': 'Escura. Tecnologica. Plataforma comunitaria onde exploradores se reunem, trocam, aprendem e brincam.',
    'Warm. Holistic. Retail and trade arm. Where sustainable makers meet conscious consumers.': 'Quente. Holistica. Braco de retalho e comercio onde criadores sustentaveis encontram consumidores conscientes.',
    'of adults feel lonely. Coraly Space is built for belonging, creativity, and connection.': 'dos adultos sentem solidao. Coraly Space foi criada para pertencimento, criatividade e conexao.',
    'COMMUNITIES': 'COMUNIDADES',
    'CREATIVITY': 'CRIATIVIDADE',
    'Everything Coraly builds is designed so people and planet thrive together.': 'Tudo que a Coraly constroi e pensado para que pessoas e planeta prosperem juntos.',
    'Peer-to-peer sustainable commerce. Buy, sell, and connect with conscious creators worldwide.': 'Comercio sustentavel entre pessoas. Compre, venda e conecte-se com criadores conscientes em todo o mundo.',
    "Organic cotton. On-demand. Zero waste. Caroline's own designs — worn with intention.": 'Algodao organico. Sob demanda. Zero desperdicio. Designs da Caroline, usados com intencao.',
    'Blog, courses, events, and community wisdom. Learn, share, and grow together.': 'Blog, cursos, eventos e sabedoria comunitaria. Aprenda, partilhe e cresca em conjunto.',
    'Eco challenges, missions, badges, gamification. Make sustainability a collective adventure.': 'Desafios eco, missoes, badges e gamificacao. Transforme a sustentabilidade numa aventura coletiva.',
    'Dance, voice, walks, and body-led creative events for real-world connection.': 'Danca, voz, caminhadas e eventos criativos corporais para conexao no mundo real.',
    'CORALY.UK · STORE': 'CORALY.UK · LOJA',
    'CORALYSPACE.COM · COMMUNITY': 'CORALYSPACE.COM · COMUNIDADE',
    'CORALYSPACE.COM · LEARN': 'CORALYSPACE.COM · APRENDER',
    'CORALYSPACE.COM · PLAY': 'CORALYSPACE.COM · JOGAR',
    'CORALYSPACE.COM · MOVE': 'CORALYSPACE.COM · MOVER',
    'ORGANIC · ON-DEMAND · ZERO WASTE': 'ORGANICO · SOB DEMANDA · ZERO DESPERDICIO',
    'PEER-TO-PEER · SUSTAINABLE': 'ENTRE PESSOAS · SUSTENTAVEL',
    'BLOG · COURSES · EVENTS': 'BLOG · CURSOS · EVENTOS',
    'CHALLENGES · MISSIONS · BADGES': 'DESAFIOS · MISSOES · BADGES',
    'DANCE · VOICE · WALKS': 'DANCA · VOZ · CAMINHADAS',
    'Shop the Collection': 'Comprar a Colecao',
    'Explore the Hub': 'Explorar o Hub',
    'Play & Earn': 'Jogar e Ganhar',
    'See Events': 'Ver Eventos',
    'There is a loneliness epidemic — 25% of adults are lonely and looking for a place of belonging. Solopreneurs and creatives feel it most acutely. Caroline built Coraly Space to be that place.': 'Existe uma epidemia de solidao — 25% dos adultos sentem-se sozinhos e procuram um lugar de pertencimento. Solopreneurs e criativos sentem isso com mais intensidade. Caroline criou Coraly Space para ser esse lugar.',
    'From dance workshops in Gloucestershire to curated sustainable retail, everything Caroline creates is designed so people and planet thrive together.': 'De workshops de danca em Gloucestershire ao retalho sustentavel curado, tudo que Caroline cria e pensado para que pessoas e planeta prosperem juntos.',
    'Female Solopreneurs': 'Solopreneurs Femininas',
    'Neurodivergent Creators': 'Criadores Neurodivergentes',
    'Parents': 'Pais',
    'LGBTQ+ Community': 'Comunidade LGBTQ+',
    'Diaspora': 'Diaspora',
    'Dancers': 'Dancarinos',
    'Creative Technologists': 'Tecnologos Criativos',
    'Universities': 'Universidades',
    'Models with Impact': 'Modelos com Impacto',
    'The Woman in Red': 'A Mulher de Vermelho',
    'Sustainability & Lifestyle': 'Sustentabilidade e Estilo de Vida',
    'Starlit forests, silent paths, warm community.': 'Florestas estreladas, caminhos silenciosos, comunidade acolhedora.',
    'Circular Economy': 'Economia Circular',
    'Autumn teaches us. Let go of what no longer serves — buy less, buy better.': 'O outono ensina-nos. Deixe ir o que ja nao serve — compre menos, compre melhor.',
    'Comfort & Wellbeing': 'Conforto e Bem-Estar',
    'The season for slowing down, warming up, and creating with intention.': 'A estacao para desacelerar, aquecer e criar com intencao.',
    'CORALY UK · SHOP': 'CORALY UK · LOJA',
    'KNOWLEDGE HUB': 'CENTRO DE CONHECIMENTO',
    'CORALYSPACE.COM · TECH': 'CORALYSPACE.COM · TECNOLOGIA',
    'CORALY.UK · HOLISTIC': 'CORALY.UK · HOLISTICO',
  },
  fr: {
    'SUSTAINABILITY ECOSYSTEM': 'ECOSYSTEME DE DURABILITE',
    'Creative': 'Creativite',
    'Curation.': 'Curation.',
    'BELONG · CONNECT · THRIVE': 'APPARTENIR · CONNECTER · S EPANOUIR',
    'COMMUNITY IN MOTION': 'COMMUNAUTE EN MOUVEMENT',
    'Explorers.': 'Explorateurs.',
    'Every one of them.': 'Chacun d eux.',
    'View All Community': 'Voir toute la communaute',
    'Meet Caroline': 'Rencontrer Caroline',
    'Our Events': 'Nos evenements',
    'ONE CORALY · TWO EXPRESSIONS': 'UNE CORALY · DEUX EXPRESSIONS',
    'The digital space': 'L espace digital',
    'and the human touch.': 'et la touche humaine.',
    'Coraly Space holds the tech-enabled community ecosystem, while Coraly UK brings the softer world of movement, care, culture, and sustainable living. Together they make the brand feel complete.': 'Coraly Space porte l ecosysteme communautaire technologique, tandis que Coraly UK apporte le monde plus doux du mouvement, du soin, de la culture et de la vie durable. Ensemble, elles completent la marque.',
    'Marketplace, knowledge, social play, and community belonging.': 'Marketplace, savoir, jeu social et appartenance communautaire.',
    'Movement, care, culture, and sustainable everyday living.': 'Mouvement, soin, culture et vie quotidienne durable.',
    'Dance, Create, Sing, Move. @coraly.space': 'Danser, creer, chanter, bouger. @coraly.space',
    'Care & Recovery': 'Soin et recuperation',
    'Creative Culture': 'Culture creative',
    'Sustainable Living': 'Vie durable',
    'Gentle rituals for carers, teachers, nurses, and burnt-out leaders.': 'Rituels doux pour aidants, enseignants, infirmiers et leaders epuises.',
    'Workshops, stories, and collaborations for makers with depth.': 'Ateliers, histoires et collaborations pour createurs avec profondeur.',
    'Low-waste style, nature-led habits, and beautiful everyday choices.': 'Style a faible dechet, habitudes guidees par la nature et beaux choix quotidiens.',
    'Learn. Share. Grow Together.': 'Apprendre. Partager. Grandir ensemble.',
    'Every season brings a new chapter. Winter is not an absence — it\'s a transformation.': 'Chaque saison apporte un nouveau chapitre. L hiver n est pas une absence — c est une transformation.',
    'Winter Wonderlands': 'Merveilles d hiver',
    'Quality Over Quantity': 'La qualite plutot que la quantite',
    'Busy Lives, Creativity & Comfort': 'Vies occupees, creativite et confort',
    'read': 'lecture',
    'Butterfly & Moon Tee': 'T-shirt Papillon et Lune',
    'Moon Phase Tee': 'T-shirt Phases de lune',
    'REWILD Tee': 'T-shirt REWILD',
    'Coral Rose Hoodie': 'Hoodie Rose Corail',
    'THE FULL RANGE': 'LA GAMME COMPLETE',
    'Little explorers,': 'Petits explorateurs,',
    'big hearts.': 'grands coeurs.',
    'Wear it.': 'Portez-le.',
    'Mean it.': 'Avec sens.',
    'Every piece.': 'Chaque piece.',
    'A statement.': 'Une declaration.',
    'Join to Shop Early': 'Rejoindre pour acheter tot',
    'Visit Teemill Store': 'Visiter la boutique Teemill',
    'ICON PIECE': 'PIECE ICONE',
    'STATEMENT PIECE': 'PIECE STATEMENT',
    'BLACK · STATEMENT · ORGANIC COTTON': 'NOIR · STATEMENT · COTON BIO',
    'Add to Bag': 'Ajouter au panier',
    'LIVE EVENTS & GATHERINGS': 'EVENEMENTS LIVE ET RENCONTRES',
    'SIGNATURE EVENT': 'EVENEMENT SIGNATURE',
    'RECURRING · IN PERSON': 'RECURRENT · EN PRESENTIEL',
    'Dance & Voice': 'Danse et voix',
    'Workshop.': 'Atelier.',
    'Book Now': 'Reserver maintenant',
    'Ask a Question': 'Poser une question',
    'WANT TO COLLABORATE?': 'ENVIE DE COLLABORER ?',
    'Host with': 'Organiser avec',
    'Get in Touch': 'Prendre contact',
    'Learn About Us': 'En savoir plus',
    'Join the Conversation': 'Rejoindre la conversation',
    'People. Planet.': 'Personnes. Planete.',
    'Profit.': 'Profit.',
    'NO ARTICLES IN THIS CATEGORY YET — CHECK BACK SOON': 'AUCUN ARTICLE DANS CETTE CATEGORIE POUR LE MOMENT — REVENEZ BIENTOT',
    'your@email.com': 'votre@email.com',
    'Marketplace': 'Marketplace',
    'Live Events': 'Evenements live',
    'Community Space': 'Espace communautaire',
    'Impact Tracking': 'Suivi d impact',
    'Adults are lonely': 'Adultes se sentent seuls',
    'Communities': 'Communautes',
    'Creativity': 'Creativite',
    'Join the Space': 'Rejoindre l espace',
    "See What's On": 'Voir le programme',
    'EVERY EXPLORER IS WELCOME': 'CHAQUE EXPLORATEUR EST BIENVENU',
    'Hybrid Events': 'Evenements hybrides',
    'Online Community': 'Communaute en ligne',
    'Curated Retail': 'Retail selectionne',
    'Yes, that\'s a community member': 'Oui, c est un membre de la communaute',
    'with the Gruffalo.': 'avec le Gruffalo.',
    'Dark. Techy. Community platform. Where explorers gather, trade, learn, and play.': 'Sombre. Tech. Plateforme communautaire ou les explorateurs se rassemblent, echangent, apprennent et jouent.',
    'Warm. Holistic. Retail and trade arm. Where sustainable makers meet conscious consumers.': 'Chaleureuse. Holistique. Branche retail et commerce ou les createurs durables rencontrent les consommateurs conscients.',
    'of adults feel lonely. Coraly Space is built for belonging, creativity, and connection.': 'des adultes se sentent seuls. Coraly Space est concu pour l appartenance, la creativite et la connexion.',
    'COMMUNITIES': 'COMMUNAUTES',
    'CREATIVITY': 'CREATIVITE',
    'Everything Coraly builds is designed so people and planet thrive together.': 'Tout ce que Coraly construit est pense pour que les personnes et la planete prosperent ensemble.',
    'Peer-to-peer sustainable commerce. Buy, sell, and connect with conscious creators worldwide.': 'Commerce durable entre pairs. Achetez, vendez et connectez-vous avec des createurs conscients dans le monde entier.',
    "Organic cotton. On-demand. Zero waste. Caroline's own designs — worn with intention.": 'Coton biologique. A la demande. Zero gaspillage. Les creations de Caroline, portees avec intention.',
    'Blog, courses, events, and community wisdom. Learn, share, and grow together.': 'Blog, cours, evenements et sagesse communautaire. Apprendre, partager et grandir ensemble.',
    'Eco challenges, missions, badges, gamification. Make sustainability a collective adventure.': 'Defis eco, missions, badges et gamification. Faire de la durabilite une aventure collective.',
    'Dance, voice, walks, and body-led creative events for real-world connection.': 'Danse, voix, marches et evenements creatifs corporels pour une connexion reelle.',
    'CORALY.UK · STORE': 'CORALY.UK · BOUTIQUE',
    'CORALYSPACE.COM · COMMUNITY': 'CORALYSPACE.COM · COMMUNAUTE',
    'CORALYSPACE.COM · LEARN': 'CORALYSPACE.COM · APPRENDRE',
    'CORALYSPACE.COM · PLAY': 'CORALYSPACE.COM · JOUER',
    'CORALYSPACE.COM · MOVE': 'CORALYSPACE.COM · BOUGER',
    'ORGANIC · ON-DEMAND · ZERO WASTE': 'BIO · A LA DEMANDE · ZERO GASPILLAGE',
    'PEER-TO-PEER · SUSTAINABLE': 'PAIR-A-PAIR · DURABLE',
    'BLOG · COURSES · EVENTS': 'BLOG · COURS · EVENEMENTS',
    'CHALLENGES · MISSIONS · BADGES': 'DEFIS · MISSIONS · BADGES',
    'DANCE · VOICE · WALKS': 'DANSE · VOIX · MARCHES',
    'Shop the Collection': 'Acheter la collection',
    'Explore the Hub': 'Explorer le hub',
    'Play & Earn': 'Jouer et gagner',
    'See Events': 'Voir les evenements',
    'There is a loneliness epidemic — 25% of adults are lonely and looking for a place of belonging. Solopreneurs and creatives feel it most acutely. Caroline built Coraly Space to be that place.': 'Il existe une epidemie de solitude — 25% des adultes se sentent seuls et cherchent un lieu d appartenance. Les solopreneurs et les creatifs le ressentent fortement. Caroline a cree Coraly Space pour etre ce lieu.',
    'From dance workshops in Gloucestershire to curated sustainable retail, everything Caroline creates is designed so people and planet thrive together.': 'Des ateliers de danse dans le Gloucestershire au retail durable selectionne, tout ce que Caroline cree est pense pour que les personnes et la planete prosperent ensemble.',
    'Female Solopreneurs': 'Solopreneures',
    'Neurodivergent Creators': 'Createurs neurodivergents',
    'Parents': 'Parents',
    'LGBTQ+ Community': 'Communaute LGBTQ+',
    'Diaspora': 'Diaspora',
    'Dancers': 'Danseurs',
    'Creative Technologists': 'Technologues creatifs',
    'Universities': 'Universites',
    'Models with Impact': 'Modeles avec impact',
    'The Woman in Red': 'La femme en rouge',
    'Sustainability & Lifestyle': 'Durabilite et lifestyle',
    'Starlit forests, silent paths, warm community.': 'Forets etoilees, chemins silencieux, communaute chaleureuse.',
    'Circular Economy': 'Economie circulaire',
    'Autumn teaches us. Let go of what no longer serves — buy less, buy better.': 'L automne nous apprend a laisser partir ce qui ne sert plus — acheter moins, acheter mieux.',
    'Comfort & Wellbeing': 'Confort et bien-etre',
    'The season for slowing down, warming up, and creating with intention.': 'La saison pour ralentir, se rechauffer et creer avec intention.',
    'CORALY UK · SHOP': 'CORALY UK · BOUTIQUE',
    'KNOWLEDGE HUB': 'CENTRE DE SAVOIR',
    'CORALYSPACE.COM · TECH': 'CORALYSPACE.COM · TECH',
    'CORALY.UK · HOLISTIC': 'CORALY.UK · HOLISTIQUE',
  },
  de: {
    'SUSTAINABILITY ECOSYSTEM': 'NACHHALTIGKEITS-OKOSYSTEM',
    'Creative': 'Kreativ',
    'Curation.': 'Kuration.',
    'BELONG · CONNECT · THRIVE': 'DAZUGEHOEREN · VERBINDEN · GEDEIHEN',
    'COMMUNITY IN MOTION': 'COMMUNITY IN BEWEGUNG',
    'Explorers.': 'Entdecker.',
    'Every one of them.': 'Jeder einzelne.',
    'View All Community': 'Ganze Community ansehen',
    'Meet Caroline': 'Caroline kennenlernen',
    'Our Events': 'Unsere Events',
    'ONE CORALY · TWO EXPRESSIONS': 'EINE CORALY · ZWEI AUSDRUCKSFORMEN',
    'The digital space': 'Der digitale Raum',
    'and the human touch.': 'und die menschliche Note.',
    'Coraly Space holds the tech-enabled community ecosystem, while Coraly UK brings the softer world of movement, care, culture, and sustainable living. Together they make the brand feel complete.': 'Coraly Space traegt das technologiegestuetzte Community-Okosystem, waehrend Coraly UK die weichere Welt von Bewegung, Care, Kultur und nachhaltigem Leben einbringt. Zusammen machen sie die Marke vollstaendig.',
    'Marketplace, knowledge, social play, and community belonging.': 'Marktplatz, Wissen, soziales Spiel und Community-Zugehoerigkeit.',
    'Movement, care, culture, and sustainable everyday living.': 'Bewegung, Care, Kultur und nachhaltiges Alltagsleben.',
    'Dance, Create, Sing, Move. @coraly.space': 'Tanzen, erschaffen, singen, bewegen. @coraly.space',
    'Care & Recovery': 'Care und Erholung',
    'Creative Culture': 'Kreative Kultur',
    'Sustainable Living': 'Nachhaltiges Leben',
    'Gentle rituals for carers, teachers, nurses, and burnt-out leaders.': 'Sanfte Rituale fuer Pflegende, Lehrkraefte, Pflegekraefte und erschoepfte Leader.',
    'Workshops, stories, and collaborations for makers with depth.': 'Workshops, Geschichten und Kollaborationen fuer Maker mit Tiefe.',
    'Low-waste style, nature-led habits, and beautiful everyday choices.': 'Abfallarmer Stil, naturgeleitete Gewohnheiten und schoene Alltagsentscheidungen.',
    'Learn. Share. Grow Together.': 'Lernen. Teilen. Gemeinsam wachsen.',
    'Every season brings a new chapter. Winter is not an absence — it\'s a transformation.': 'Jede Jahreszeit bringt ein neues Kapitel. Winter ist keine Abwesenheit — er ist Verwandlung.',
    'Winter Wonderlands': 'Winterwunderwelten',
    'Quality Over Quantity': 'Qualitaet statt Quantitaet',
    'Busy Lives, Creativity & Comfort': 'Volle Leben, Kreativitaet und Komfort',
    'read': 'Lesezeit',
    'Butterfly & Moon Tee': 'Butterfly & Moon T-Shirt',
    'Moon Phase Tee': 'Moon Phase T-Shirt',
    'REWILD Tee': 'REWILD T-Shirt',
    'Coral Rose Hoodie': 'Coral Rose Hoodie',
    'THE FULL RANGE': 'DIE GANZE AUSWAHL',
    'Little explorers,': 'Kleine Entdecker,',
    'big hearts.': 'grosse Herzen.',
    'Wear it.': 'Trage es.',
    'Mean it.': 'Meine es ernst.',
    'Every piece.': 'Jedes Stueck.',
    'A statement.': 'Ein Statement.',
    'Join to Shop Early': 'Beitreten und frueh shoppen',
    'Visit Teemill Store': 'Teemill Store besuchen',
    'ICON PIECE': 'IKONISCHES STUECK',
    'STATEMENT PIECE': 'STATEMENT-STUECK',
    'BLACK · STATEMENT · ORGANIC COTTON': 'SCHWARZ · STATEMENT · BIO-BAUMWOLLE',
    'Add to Bag': 'In den Warenkorb',
    'LIVE EVENTS & GATHERINGS': 'LIVE-EVENTS UND TREFFEN',
    'SIGNATURE EVENT': 'SIGNATURE-EVENT',
    'RECURRING · IN PERSON': 'REGELMAESSIG · VOR ORT',
    'Dance & Voice': 'Tanz und Stimme',
    'Workshop.': 'Workshop.',
    'Book Now': 'Jetzt buchen',
    'Ask a Question': 'Frage stellen',
    'WANT TO COLLABORATE?': 'MOECHTEST DU KOOPERIEREN?',
    'Host with': 'Veranstalten mit',
    'Get in Touch': 'Kontakt aufnehmen',
    'Learn About Us': 'Mehr ueber uns',
    'Join the Conversation': 'Gespräch beitreten',
    'People. Planet.': 'Menschen. Planet.',
    'Profit.': 'Profit.',
    'NO ARTICLES IN THIS CATEGORY YET — CHECK BACK SOON': 'NOCH KEINE ARTIKEL IN DIESER KATEGORIE — SCHAU BALD WIEDER VORBEI',
    'your@email.com': 'deine@email.com',
    'Marketplace': 'Marktplatz',
    'Live Events': 'Live-Events',
    'Community Space': 'Community-Raum',
    'Impact Tracking': 'Impact-Tracking',
    'Adults are lonely': 'Erwachsene sind einsam',
    'Communities': 'Communities',
    'Creativity': 'Kreativitaet',
    'Join the Space': 'Dem Space beitreten',
    "See What's On": 'Programm ansehen',
    'EVERY EXPLORER IS WELCOME': 'JEDER ENTDECKER IST WILLKOMMEN',
    'Hybrid Events': 'Hybride Events',
    'Online Community': 'Online-Community',
    'Curated Retail': 'Kuratierter Retail',
    'Yes, that\'s a community member': 'Ja, das ist ein Community-Mitglied',
    'with the Gruffalo.': 'mit dem Gruffalo.',
    'Dark. Techy. Community platform. Where explorers gather, trade, learn, and play.': 'Dunkel. Techy. Community-Plattform, wo Entdecker zusammenkommen, handeln, lernen und spielen.',
    'Warm. Holistic. Retail and trade arm. Where sustainable makers meet conscious consumers.': 'Warm. Holistisch. Retail- und Handelsbereich, wo nachhaltige Maker bewusste Konsumenten treffen.',
    'of adults feel lonely. Coraly Space is built for belonging, creativity, and connection.': 'der Erwachsenen fuehlen sich einsam. Coraly Space ist fuer Zugehoerigkeit, Kreativitaet und Verbindung gebaut.',
    'COMMUNITIES': 'COMMUNITIES',
    'CREATIVITY': 'KREATIVITAET',
    'Everything Coraly builds is designed so people and planet thrive together.': 'Alles, was Coraly baut, ist darauf ausgelegt, dass Menschen und Planet gemeinsam gedeihen.',
    'Peer-to-peer sustainable commerce. Buy, sell, and connect with conscious creators worldwide.': 'Nachhaltiger Peer-to-Peer-Handel. Kaufe, verkaufe und verbinde dich weltweit mit bewussten Kreativen.',
    "Organic cotton. On-demand. Zero waste. Caroline's own designs — worn with intention.": 'Bio-Baumwolle. Auf Abruf. Kein Abfall. Carolines eigene Designs — mit Intention getragen.',
    'Blog, courses, events, and community wisdom. Learn, share, and grow together.': 'Blog, Kurse, Events und Community-Weisheit. Lernen, teilen und gemeinsam wachsen.',
    'Eco challenges, missions, badges, gamification. Make sustainability a collective adventure.': 'Eco-Challenges, Missionen, Badges und Gamification. Nachhaltigkeit als gemeinsames Abenteuer.',
    'Dance, voice, walks, and body-led creative events for real-world connection.': 'Tanz, Stimme, Spaziergaenge und koerperbasierte kreative Events fuer echte Verbindung.',
    'CORALY.UK · STORE': 'CORALY.UK · SHOP',
    'CORALYSPACE.COM · COMMUNITY': 'CORALYSPACE.COM · COMMUNITY',
    'CORALYSPACE.COM · LEARN': 'CORALYSPACE.COM · LERNEN',
    'CORALYSPACE.COM · PLAY': 'CORALYSPACE.COM · SPIELEN',
    'CORALYSPACE.COM · MOVE': 'CORALYSPACE.COM · BEWEGEN',
    'ORGANIC · ON-DEMAND · ZERO WASTE': 'BIO · AUF ABRUF · KEIN ABFALL',
    'PEER-TO-PEER · SUSTAINABLE': 'PEER-TO-PEER · NACHHALTIG',
    'BLOG · COURSES · EVENTS': 'BLOG · KURSE · EVENTS',
    'CHALLENGES · MISSIONS · BADGES': 'CHALLENGES · MISSIONEN · BADGES',
    'DANCE · VOICE · WALKS': 'TANZ · STIMME · SPAZIERGAENGE',
    'Shop the Collection': 'Kollektion shoppen',
    'Explore the Hub': 'Hub erkunden',
    'Play & Earn': 'Spielen und verdienen',
    'See Events': 'Events ansehen',
    'There is a loneliness epidemic — 25% of adults are lonely and looking for a place of belonging. Solopreneurs and creatives feel it most acutely. Caroline built Coraly Space to be that place.': 'Es gibt eine Einsamkeitsepidemie — 25% der Erwachsenen sind einsam und suchen einen Ort der Zugehoerigkeit. Solopreneure und Kreative spueren das besonders stark. Caroline hat Coraly Space geschaffen, um dieser Ort zu sein.',
    'From dance workshops in Gloucestershire to curated sustainable retail, everything Caroline creates is designed so people and planet thrive together.': 'Von Tanzworkshops in Gloucestershire bis zu kuratiertem nachhaltigem Retail: Alles, was Caroline erschafft, ist darauf ausgelegt, dass Menschen und Planet gemeinsam gedeihen.',
    'Female Solopreneurs': 'Weibliche Solopreneure',
    'Neurodivergent Creators': 'Neurodivergente Kreative',
    'Parents': 'Eltern',
    'LGBTQ+ Community': 'LGBTQ+ Community',
    'Diaspora': 'Diaspora',
    'Dancers': 'Taenzer',
    'Creative Technologists': 'Kreative Technologen',
    'Universities': 'Universitaeten',
    'Models with Impact': 'Models mit Wirkung',
    'The Woman in Red': 'Die Frau in Rot',
    'Sustainability & Lifestyle': 'Nachhaltigkeit und Lifestyle',
    'Starlit forests, silent paths, warm community.': 'Sternenwaelder, stille Wege, warme Community.',
    'Circular Economy': 'Kreislaufwirtschaft',
    'Autumn teaches us. Let go of what no longer serves — buy less, buy better.': 'Der Herbst lehrt uns, loszulassen, was nicht mehr dient — weniger kaufen, besser kaufen.',
    'Comfort & Wellbeing': 'Komfort und Wohlbefinden',
    'The season for slowing down, warming up, and creating with intention.': 'Die Jahreszeit zum Verlangsamen, Aufwaermen und bewussten Erschaffen.',
    'CORALY UK · SHOP': 'CORALY UK · SHOP',
    'KNOWLEDGE HUB': 'WISSENSZENTRUM',
    'CORALYSPACE.COM · TECH': 'CORALYSPACE.COM · TECH',
    'CORALY.UK · HOLISTIC': 'CORALY.UK · HOLISTISCH',
  },
};

const originalText = new WeakMap<Text, string>();
const originalAttributes = new WeakMap<Element, Record<string, string>>();
const TRANSLATABLE_ATTRIBUTES = ['placeholder', 'title', 'aria-label', 'alt'] as const;

function getPhraseMap(lang: Exclude<LanguageCode, 'en'>) {
  return { ...PHRASE_TRANSLATIONS[lang], ...EXTRA_PHRASE_TRANSLATIONS[lang] };
}

const allPhraseMaps = (['pt', 'fr', 'de'] as const).map(getPhraseMap);
const phraseSources = Object.keys({ ...PHRASE_TRANSLATIONS.pt, ...EXTRA_PHRASE_TRANSLATIONS.pt }).sort((a, b) => b.length - a.length);

const translatedToEnglish = allPhraseMaps.reduce<Record<string, string>>((acc, phraseMap) => {
  Object.entries(phraseMap).forEach(([english, translated]) => {
    acc[translated] = english;
  });
  return acc;
}, {});

function getSourceText(text: string) {
  const trimmed = text.trim();
  return translatedToEnglish[trimmed] ?? trimmed;
}

function isKnownTranslationFor(source: string, current: string) {
  if (source === current) return true;
  return allPhraseMaps.some(phraseMap => phraseMap[source] === current);
}

function translateString(value: string, lang: LanguageCode) {
  const phraseMap = lang === 'en' ? null : getPhraseMap(lang);
  const source = getSourceText(value);
  const trimmed = source.trim();
  if (!trimmed) return source;
  const exact = phraseMap?.[trimmed];
  if (exact) return source.replace(trimmed, exact);

  let translated = source;
  for (const phrase of phraseSources) {
    const replacement = phraseMap?.[phrase];
    if (!replacement || !translated.includes(phrase)) continue;
    translated = translated.split(phrase).join(replacement);
  }
  return translated;
}

function translateAttributes(lang: LanguageCode) {
  if (typeof document === 'undefined') return;
  document.querySelectorAll<HTMLElement>('[placeholder], [title], [aria-label], img[alt]').forEach((element) => {
    if (element.closest('[data-no-translate="true"]')) return;
    const originals = originalAttributes.get(element) ?? {};
    TRANSLATABLE_ATTRIBUTES.forEach((attribute) => {
      const current = element.getAttribute(attribute);
      if (!current?.trim()) return;
      if (!originals[attribute]) originals[attribute] = getSourceText(current);
      const translated = translateString(originals[attribute], lang);
      if (current !== translated) element.setAttribute(attribute, translated);
    });
    originalAttributes.set(element, originals);
  });
}

function translateVisibleText(lang: LanguageCode) {
  if (typeof document === 'undefined') return;
  const walker = document.createTreeWalker(document.body, NodeFilter.SHOW_TEXT, {
    acceptNode(node) {
      const parent = node.parentElement;
      if (!parent) return NodeFilter.FILTER_REJECT;
      if (['SCRIPT', 'STYLE', 'NOSCRIPT', 'TEXTAREA'].includes(parent.tagName)) return NodeFilter.FILTER_REJECT;
      if (parent.closest('[data-no-translate="true"], input, select, option, button[aria-label]')) {
        return NodeFilter.FILTER_REJECT;
      }
      if (!node.textContent?.trim()) return NodeFilter.FILTER_REJECT;
      return NodeFilter.FILTER_ACCEPT;
    },
  });

  const nodes: Text[] = [];
  while (walker.nextNode()) nodes.push(walker.currentNode as Text);

  for (const node of nodes) {
    const currentText = node.textContent ?? '';
    const currentTrimmed = currentText.trim();
    const cachedSource = originalText.get(node);
    const source = cachedSource && isKnownTranslationFor(cachedSource.trim(), currentTrimmed)
      ? cachedSource
      : getSourceText(currentText);
    originalText.set(node, source);
    const trimmed = source.trim();
    if (!trimmed) continue;
    const translatedText = translateString(source, lang);
    if (node.textContent !== translatedText) node.textContent = translatedText;
  }

  translateAttributes(lang);
}

const ExperienceContext = createContext<ExperienceContextValue | null>(null);

export function CoralyExperienceProvider({ children }: { children: ReactNode }) {
  const [theme, setTheme] = useState<ThemeName>('dark');
  const [lang, setLang] = useState<LanguageCode>('en');

  useEffect(() => {
    const storedTheme = window.localStorage.getItem('coraly-theme');
    const storedLang = window.localStorage.getItem('coraly-lang');
    if (storedTheme === 'dark' || storedTheme === 'light') setTheme(storedTheme);
    if (storedLang === 'en' || storedLang === 'pt' || storedLang === 'fr' || storedLang === 'de') {
      setLang(storedLang);
    }
  }, []);

  useEffect(() => {
    document.documentElement.dataset.theme = theme;
    window.localStorage.setItem('coraly-theme', theme);
  }, [theme]);

  useEffect(() => {
    document.documentElement.lang = lang;
    window.localStorage.setItem('coraly-lang', lang);
    window.requestAnimationFrame(() => translateVisibleText(lang));
  }, [lang]);

  useEffect(() => {
    const observer = new MutationObserver(() => {
      window.requestAnimationFrame(() => translateVisibleText(lang));
    });
    observer.observe(document.body, { childList: true, subtree: true, characterData: true, attributes: true, attributeFilter: [...TRANSLATABLE_ATTRIBUTES] });
    return () => observer.disconnect();
  }, [lang]);

  const value = useMemo<ExperienceContextValue>(() => ({
    theme,
    setTheme,
    toggleTheme: () => setTheme(current => current === 'dark' ? 'light' : 'dark'),
    lang,
    setLang,
    t: (key) => TRANSLATIONS[lang][key] ?? TRANSLATIONS.en[key] ?? key,
  }), [theme, lang]);

  return (
    <ExperienceContext.Provider value={value}>
      {children}
    </ExperienceContext.Provider>
  );
}

export function useCoralyExperience() {
  const context = useContext(ExperienceContext);
  if (!context) {
    throw new Error('useCoralyExperience must be used inside CoralyExperienceProvider');
  }
  return context;
}

export function ThemeToggle() {
  const { theme, toggleTheme } = useCoralyExperience();
  const isDark = theme === 'dark';

  return (
    <button
      type="button"
      className="theme-toggle"
      data-no-translate="true"
      onClick={toggleTheme}
      title={isDark ? 'Switch to light holistic theme' : 'Switch to dark ecosystem theme'}
      aria-label={isDark ? 'Switch to light holistic theme' : 'Switch to dark ecosystem theme'}
    >
      <span className="theme-toggle__icon" aria-hidden>{isDark ? 'Moon' : 'Sun'}</span>
      <span className="theme-toggle__track" aria-hidden>
        <span className="theme-toggle__thumb" />
      </span>
      <span className="theme-toggle__label">{isDark ? 'Dark' : 'Light'}</span>
    </button>
  );
}

export function LanguageSwitcher() {
  const { lang, setLang } = useCoralyExperience();
  const [open, setOpen] = useState(false);
  const current = LANGUAGES.find(item => item.code === lang) ?? LANGUAGES[0];

  return (
    <div className="lang-switcher" data-no-translate="true">
      <button
        type="button"
        className="lang-switcher__button"
        aria-expanded={open}
        aria-label="Change language"
        onClick={() => setOpen(value => !value)}
      >
        <span>{current.flag}</span>
        <span>{current.label}</span>
        <span aria-hidden>v</span>
      </button>
      {open && (
        <div className="lang-switcher__menu">
          {LANGUAGES.map(item => (
            <button
              key={item.code}
              type="button"
              className={item.code === lang ? 'is-active' : ''}
              onClick={() => {
                setLang(item.code);
                setOpen(false);
              }}
            >
              <span>{item.flag}</span>
              <span>{item.name}</span>
            </button>
          ))}
        </div>
      )}
    </div>
  );
}
