// Unified Coraly Space image manifest
// Batches 2 & 3 (embedded in CoralySpace.jsx, extracted to src/lib/extracted-images.js)
// Batch 4 (from src/lib/coraly-images-manifest.js)
// Usage: import { IMAGES } from '@/lib/coraly-images-manifest'

export {
  B2_CAROLINE_MODEL, B2_CAROLINE_GRUFFALO, B2_GRUFFALO_ART,
  B2_LOGO_DARK, B2_LOGO_LIGHT, B2_REWILD_TEE, B2_MENS_TEE,
  B2_BLACK_BUTTERFLY, B2_SPACE_OVAL, B2_BRAND_SHEET,
  B3_MODEL_COAST, B3_CAROLINE_RIVER, B3_CAROLINE_FIELD,
  B3_CAROLINE_SNOW, B3_CAROLINE_AUTUMN, B3_DANCE_EVENT,
  B3_AUTUMN_LEAVES, B3_WINTER_COSY, B3_WINTER_STARS, B3_WINTER_PATH,
  B3_LOGO_UK_PREMIUM, B3_ADVENTURE_GRAPHIC,
  P_MOON_PHASE, P_FOX_GLOVE, P_BUTTERFLY_PINK, P_SUNSHINE,
  P_CORAL_ROSE, P_BUTTERFLY_KIDS, P_COLLECTION, P_BUTTERFLIES_NAVY,
  P_SCARLETT, P_FOX_ADULT, P_DEER, P_ASYMMETRIC_BF,
  P_BUTTERFLY_MOON, P_ROSE_HAND,
} from '../src/lib/extracted-images.js';

export {
  LOGO_CORALY_CREATIVE_CURATION, LOGO_CORALY_SPACE_CORAL_ICON,
  BRAND_HERO_HEART_LEAF, BRAND_CTA_EXPLORE_CREATE,
  BRAND_VENN_SUSTAINABILITY, BRAND_QUOTE_GOOD_DAY,
  MARKETING_SUSTAINABLE_COLLECTION, MODEL_LISBON_GREY_BUTTERFLY,
  LIFESTYLE_GUITAR_WALK, LIFESTYLE_COFFEE_CHOCOLATE, LIFESTYLE_ORCHID_CANDLE,
  BG_WINTER_PINE_SNOW, BG_WINTER_NIGHT_STARS, BG_WINTER_TYPO_SNOW,
  BG_RAINBOW_SKY, BG_AUTUMN_LEAVES_SUN, BG_SUNSET_SKY_TREE, BG_FOREST_PATH_SUNSET,
} from '../src/lib/coraly-images-manifest';

import {
  B2_LOGO_DARK, B2_LOGO_LIGHT, B2_GRUFFALO_ART, B3_LOGO_UK_PREMIUM,
  B3_CAROLINE_RIVER, B3_CAROLINE_FIELD, B3_CAROLINE_AUTUMN, B3_CAROLINE_SNOW,
  B2_CAROLINE_GRUFFALO, B3_MODEL_COAST, B3_DANCE_EVENT,
  B2_REWILD_TEE, P_BUTTERFLY_MOON, P_MOON_PHASE, P_CORAL_ROSE,
  B2_BRAND_SHEET, B3_WINTER_STARS, B3_AUTUMN_LEAVES, B3_WINTER_COSY,
  B3_WINTER_PATH, B3_ADVENTURE_GRAPHIC,
  P_BUTTERFLIES_NAVY, P_FOX_ADULT, P_DEER, P_ROSE_HAND,
  B2_CAROLINE_MODEL, P_COLLECTION,
} from '../src/lib/extracted-images.js';

// Canonical IMAGES object — matches CLAUDE.md naming convention
export const IMAGES = {
  // Logos
  LOGO_SPACE_DARK: B2_LOGO_DARK,
  LOGO_SPACE_LIGHT: B2_LOGO_LIGHT,
  LOGO_UK_PREMIUM: B3_LOGO_UK_PREMIUM,
  // Caroline shots
  HERO_MOTION: '/hero-motion.mp4',
  CAROLINE_RIVER: B3_CAROLINE_RIVER,
  CAROLINE_FIELD: B3_CAROLINE_FIELD,
  CAROLINE_AUTUMN: B3_CAROLINE_AUTUMN,
  CAROLINE_SNOW: B3_CAROLINE_SNOW,
  CAROLINE_GRUFFALO: B2_CAROLINE_GRUFFALO,
  CAROLINE_MODEL: B2_CAROLINE_MODEL,
  // Models
  MODEL_COAST: B3_MODEL_COAST,
  MODEL_LISBON_SCULPTURE: '/model-lisbon-sculpture.png',
  // Brand assets
  BRAND_EXPLORE_CREATE: '/explore-create-coraly-space.png',
  BRAND_CORALY_UK_SHIRT_MOTION: '/coraly-uk-shirt.gif',
  BRAND_CREATE_CC_MOTION: '/createcc.gif',
  BRAND_GRUFFALO_ART: B2_GRUFFALO_ART,
  BRAND_DANCE_EVENT: B3_DANCE_EVENT,
  BRAND_ADVENTURE: B3_ADVENTURE_GRAPHIC,
  BRAND_COLLECTION: B2_BRAND_SHEET,
  // Products
  PRODUCT_REWILD_SHOWCASE: '/rewild-tee-showcase.png',
  PRODUCT_REWILD: B2_REWILD_TEE,
  PRODUCT_BUTTERFLY_MOON: P_BUTTERFLY_MOON,
  PRODUCT_MOON_PHASE: P_MOON_PHASE,
  PRODUCT_CORAL_ROSE: P_CORAL_ROSE,
  PRODUCT_BUTTERFLIES_NAVY: P_BUTTERFLIES_NAVY,
  PRODUCT_FOX_ADULT: P_FOX_ADULT,
  PRODUCT_DEER: P_DEER,
  PRODUCT_ROSE_HAND: P_ROSE_HAND,
  PRODUCT_COLLECTION: P_COLLECTION,
  // Blog / nature
  BLOG_WINTER_STARS: B3_WINTER_STARS,
  BLOG_AUTUMN_LEAVES: B3_AUTUMN_LEAVES,
  BLOG_WINTER_COSY: B3_WINTER_COSY,
  BLOG_WINTER_PATH: B3_WINTER_PATH,
} as const;
